'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("InventoryControlSystem.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bgChangePassword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgChangePassword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bgCreateUserAccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgCreateUserAccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bgPriceSetting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgPriceSetting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bgProducts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgProducts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bgQuantityDivision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgQuantityDivision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bgReports() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgReports", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bgSales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgSales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bguseraccount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bguseraccount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bguseraccount1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bguseraccount1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnBackUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBackUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnBackUp2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnBackUp2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnPassword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPassword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnPassword2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPassword2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnProducts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnProducts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnProducts2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnProducts2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnPurchase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPurchase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnPurchase2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPurchase2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnReports() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnReports", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btnReports2() As System.Dra ~dulla^@204~ ~dulla^@204~ t
                Dim obj As Object ~dulla^@204~ ager.GetObject("btnReports2", resourc~dulla^@204~               Return CType(obj,System~dulla^@204~ ap)
            End Get
        End~dulla^@204~       
        Friend ReadOnly Prope~dulla^@204~ ) As System.Drawing.Bitmap
         ~dulla^@204~            Dim obj As Object = Resour~dulla^@204~ Object("btnSales", resourceCulture)
~dulla^@204~    Return CType(obj,System.Drawing.Bi~dulla^@204~       End Get
        End Property
~dulla^@204~      Friend ReadOnly Property btnSale~dulla^@204~ m.Drawing.Bitmap
            Get
  ~dulla^@204~  Dim obj As Object = ResourceManager.~dulla^@204~ nSales2", resourceCulture)
         ~dulla^@204~  CType(obj,System.Drawing.Bitmap)
  ~dulla^@204~  Get
        End Property
        ~dulla^@204~ nd ReadOnly Property btnUsers() As Sy~dulla^@204~ Bitmap
            Get
            ~dulla^@204~ s Object = ResourceManager.GetObject(~dulla^@204~ esourceCulture)
                Retu~dulla^@204~ System.Drawing.Bitmap)
            E~dulla^@204~    End Property
        
        Fr~dulla^@204~  Property btnUsers2() As System.Drawi~dulla^@204~           Get
                Dim ob~dulla^@204~  ResourceManager.GetObject("btnUsers2~dulla^@204~ lture)
                Return CType(~dulla^@204~ awing.Bitmap)
            End Get
 ~dulla^@204~ operty
        
        Friend Read~dulla^@204~  close() As System.Drawing.Bitmap
  ~dulla^@204~ 
                Dim obj As Object =~dulla^@204~ ger.GetObject("close", resourceCultur~dulla^@204~        Return CType(obj,System.Drawin~dulla^@204~           End Get
        End Proper~dulla^@204~ 
        Friend ReadOnly Property hel~dulla^@204~ m.Drawing.Bitmap
            Get
  ~dulla^@204~  Dim obj As Object = ResourceManager.~dulla^@204~ lpb", resourceCulture)
             ~dulla^@204~ pe(obj,System.Drawing.Bitmap)
      ~dulla^@204~ 
        End Property
        
   ~dulla^@204~ eadOnly Property home() As System.Dra~dulla^@204~             Get
                Dim ~dulla^@204~  = ResourceManager.GetObject("home", ~dulla^@204~ re)
                Return CType(obj~dulla^@204~ ng.Bitmap)
            End Get
    ~dulla^@204~ rty
        
        Friend ReadOnl~dulla^@204~ gin() As System.Drawing.Bitmap
     ~dulla^@204~                Dim obj As Object = Re~dulla^@204~ .GetObject("login", resourceCulture)~dulla^@204~     Return CType(obj,System.Drawing.B~dulla^@204~        End Get
        End Property~dulla^@204~       Friend ReadOnly Property login1~dulla^@204~ Drawing.Bitmap
            Get
    ~dulla^@204~ im obj As Object = ResourceManager.Ge~dulla^@204~ n1", resourceCulture)
              ~dulla^@204~ e(obj,System.Drawing.Bitmap)
       ~dulla^@204~ 
        End Property
        
    ~dulla^@204~ adOnly Property MAINMENU() As System.~dulla^@204~ p
            Get
                D~dulla^@204~ ect = ResourceManager.GetObject("MAIN~dulla^@204~ ceCulture)
                Return CT~dulla^@204~ m.Drawing.Bitmap)
            End Ge~dulla^@204~ d Property
        
        Friend ~dulla^@204~ erty MANIMENU() As System.Drawing.Bit~dulla^@204~     Get
                Dim obj As O~dulla^@204~ rceManager.GetObject("MANIMENU", reso~dulla^@204~ 
                Return CType(obj,Sys~dulla^@204~ itmap)
            End Get
        ~dulla^@204~ 
        
        Friend ReadOnly Pr~dulla^@204~ ze() As System.Drawing.Bitmap
      ~dulla^@204~               Dim obj As Object = Res~dulla^@204~ GetObject("minimize", resourceCulture~dulla^@204~       Return CType(obj,System.Drawing~dulla^@204~          End Get
        End Propert~dulla^@204~         Friend ReadOnly Property Prod~dulla^@204~ tem.Drawing.Bitmap
            Get
~dulla^@204~    Dim obj As Object = ResourceManage~dulla^@204~ Products", resourceCulture)
        ~dulla^@204~ n CType(obj,System.Drawing.Bitmap)
 ~dulla^@204~ d Get
        End Property
        ~dulla^@204~ end ReadOnly Property window() As Sys~dulla^@204~ itmap
            Get
             ~dulla^@204~  Object = ResourceManager.GetObject("~dulla^@204~ urceCulture)
                Return ~dulla^@204~ tem.Drawing.Bitmap)
            End ~dulla^@204~ End Property
    End Module
End Namespace
